theme: minima
title: Movimento 5 Stelle
description: sito open source con tutti i contatti base per il Movimento 5 Stelle 2050
show_excerpts: false # set to true to show excerpts on the homepage

#header_pages:
#  - toscana.md
  
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/movimento5s/" }

plugins:
 - jekyll-feed
 - jekyll-seo-tag
