title: "M5SË£"
description: sito open source con tutti i contatti base per il Movimento 5 Stelle 2050
remote_theme: just-the-docs/just-the-docs

color_scheme: "light"
search_enabled: false

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Enable or disable heading anchors
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "by attivisti M5S++ | partecipa!"

kramdown:
  toc_levels: 1..2