site_name: M5Sx Formazione Partecipazione Innovazione 
site_url: https://2050x.org
site_author: Stefano Cecere
site_description: 2050x è uno spazio formativo di cittadini attivi del M5S che vogliono migliorarsi per migliorare il mondo, possibilmente < 2050

copyright: <a href="/info/">chi siamo a gestire questo bellissimo sito?</a> - <a href="/info/#licenza">licenza Creative Commons</a> - <a href="/contatto">newsletter</a>

theme:
  name: material
  custom_dir: overrides
  language: it
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.indexes
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - tables
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Plugins
plugins:
  - search:
      lang: it
  - social:
      cards_color:
        fill: "#14608E" 
        text: "#FFFFFF"
  - table-reader
  - minify:
      minify_html: true
  - awesome-pages
  - tags:
      tags_file: info/tags.md
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: date
      locale: it
      enable_creation_date: false
      exclude:
        - index.md

repo_url: https://github.com/2050x/2050x.org
edit_uri: edit/main/docs/
repo_name: GitHub/2050x.org

extra_css:
  - assets/stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-6CTL17N8TN
  social:
    - icon: fontawesome/brands/telegram 
      link: https://t.me/org2050x
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/groups/2050x
#    - icon: fontawesome/brands/github 
#      link: https://github.com/2050x
#    - icon: fontawesome/brands/discord 
#      link: https://discord.gg/VUjgGtDgAh
  consent:
    title: Accettazione Cookie
    description: >- 
      Questo sito usa alcuni cookies per garantire la migliore esperienza di navigazione. Niente di speciale.
