site_name: 2050x Spazio Attivisti Movimento 5 Stelle
site_url: https://2050x.org
site_author: Stefano Cecere & M5S++
site_description: uno spazio opensource degli attivisti per gli attivisti del M5S con informazioni, risorse e giochi formativi.

copyright: <a href="/about">Sito Open Source e Creative Commons creato dal team M5S++.</a> 

#nav:
#  - Manuale:
#    - 'Writing your docs': 'manuale-attivista/coinvolgimento.md'
#    - 'Styling your docs': 'manuale-attivista/comunicazione.md'

theme:
  name: material
  language: it
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - tables
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list

# Plugins
plugins:
  - search:
      lang: it
  - social
  - table-reader
  - minify:
      minify_html: true

repo_url: https://github.com/m5sx/m5sx.github.io
edit_uri: edit/main/docs/

extra_css:
  - assets/stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-6CTL17N8TN
  consent:
    title: Accettazione Cookie
    description: >- 
      Questo sito usa alcuni cookies per garantire la migliore esperienza di navigazione. Niente di speciale.
