site_name: 2050x Formazione Attivisti M5S++
site_url: https://2050x.org
site_author: Stefano Cecere & M5S++
site_description: uno spazio formativo opensource degli attivisti per gli attivisti e la cittadinanza attiva (del Movimento 5 Stelle ma non solo) che vogliono migliorarsi con informazioni, risorse e giochi.

copyright: sito <a href="/info/about">Open Source</a> - <a href="/info/licenza">licenza Creative Commons</a> - <a href="/info/contatto">newsletter</a>

theme:
  name: material
  custom_dir: overrides
  language: it
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - announce.dismiss
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - tables
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Plugins
plugins:
  - search:
      lang: it
  - social:
      cards_color:
        fill: "#14608E" 
        text: "#FFFFFF"
  - table-reader
  - minify:
      minify_html: true

repo_url: https://github.com/2050x/2050x.org
edit_uri: edit/main/docs/

extra_css:
  - assets/stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-6CTL17N8TN
  social:
    - icon: fontawesome/brands/telegram 
      link: https://t.me/org2050x
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/VUjgGtDgAh
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/groups/2050x
    - icon: fontawesome/brands/github 
      link: https://github.com/2050x
  consent:
    title: Accettazione Cookie
    description: >- 
      Questo sito usa alcuni cookies per garantire la migliore esperienza di navigazione. Niente di speciale.
